name: EduardAPI
description: API de desenvolvimento de plugins que facilita sua vida
main: net.eduard.api.EduardAPI
version: 2.4.5
author: Eduard
authors: [Eduard]
soft-depend: [Essentials,Vault,McMMO]
website: https://www.youtube.com/user/EduTutoriaisHD
commands:
  map:
    description: Controle dos Mapas da API
    aliases: [mapa]
    usage: /<command> help
  config:
    description: Controle das Configs da API
    aliases: [configs,config]
    usage: /<command> help
  api:
    description: Comando principal da API
    aliases: [eduardapi,eduard,e]
    usage: /<command> help
  goto: 
    description: Teleporta para outro mundo
    aliases: [ir,irpara,mundo,world]
    usage: /<command> <world>
  enchantment: 
    description: Encantar os itens
    aliases: [ench]
    usage: /<command> <enchant> <level>
  sound: 
    description: Tocar um som do minecraft
    aliases: [som]
    usage: /<command> <sound> [volume] [pitch]