rootProject.name = "eduardapi"
include(":JavaUtils")
include(":MineUtils")
include(":SQLManager")
include(":MineNMS")
include(":MineNMS-1_8_9")
include(":MineNMS-1_7")
include(":MineNMS-1_12")
include(":MineNMS-1_16_5")
include(":MinigameLib")
include(":StorageLib")
